# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:
  
env:
  IMAGE_NAME: "TEST_IMAGE"
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo {{ $IMAGE_TAG }} and {{ env.IMAGE_TAG }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
