# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:
  
env:
  IMAGE_NAME: "TEST_IMAGE"
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump Github Context
        env:
          GH_CONTEXT: ${{ toJSON(github) }}
        run: echo $GH_CONTEXT
      
      - name: Run a one-line script
        run: echo runID:$GITHUB_RUN_ID, workspace:$GITHUB_WORKSPACE

      - name: Run a multi-line script
        if: ${{ github.event && github.workflow && github.actor && github.repository && github.event_name && github.sha && github.ref && github.head_ref && github.base_ref }}
        run: |
          echo event:$GITHUB_EVENT, workflow:$GITHUB_WORKFLOW, actor:$GITHUB_ACTOR, repo:$GITHUB_REPOSITORY, event_name:$GITHUB_EVENT_NAME, ref=$GITHUB_REF, head_ref=$GITHUB_HEAD_REF, base_ref=$GITHUB_BASE_REF

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
